# Generated by Django 6.1 on 2026-09-01 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classroom_class_teacher_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='full_marks_practical',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='full_marks_theory',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='pass_marks_practical',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='pass_marks_theory',
        ),
        migrations.AddField(
            model_name='subject',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='subject',
            name='full_marks',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='pass_marks',
            field=models.FloatField(default=35.0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credit_hours',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=4),
        ),
    ]
