# Generated by Django 6.1 on 2026-09-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_subject_full_marks_practical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='full_marks_practical',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='subject',
            name='full_marks_theory',
            field=models.FloatField(default=75.0),
        ),
        migrations.AddField(
            model_name='subject',
            name='pass_marks_practical',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='subject',
            name='pass_marks_theory',
            field=models.FloatField(default=27.0),
        ),
    ]
